import Footer from "@/components/footer/footer";
import { Header, TopHeader } from "@/components/header";
import { primaryColor } from "@/constants";
import { RootProviders } from "@/provider";
import type { Metadata, Viewport } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { Marcellus, Poppins } from "next/font/google";
import "../globals.css";

const marcellusFont = Marcellus({
	variable: "--font-marcellus",
	subsets: ["latin"],
	weight: ["400"],
});

const poppinsFont = Poppins({
	variable: "--font-poppins",
	subsets: ["latin"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export const viewport: Viewport = {
	themeColor: primaryColor,
};

export default async function RootLayout({
	children,
	params: { locale },
}: Readonly<{
	children: React.ReactNode;
	params: { locale: string };
}>) {
	const messages = await getMessages();
	return (
		<html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
			<body
				className={`${marcellusFont.variable} ${poppinsFont.variable} antialiased`}
			>
				<NextIntlClientProvider messages={messages}>
					<RootProviders>
						<TopHeader />
						<Header />
						{children}
						<Footer />
					</RootProviders>
				</NextIntlClientProvider>
			</body>
		</html>
	);
}
